name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  checks: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - name: install packages
        run: pipenv sync --dev
      - name: run test
        run: pipenv run pytest -q --junit-xml pytest.xml
        continue-on-error: true
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: 'pytest.xml'
